// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: routeguide/routeguide.proto

package routeguide

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Point represents a geographical coordinate pair
type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      int32                  `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     int32                  `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_routeguide_routeguide_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_routeguide_routeguide_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_routeguide_routeguide_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Point) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// Feature represents a named geographical location
type Feature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location      *Point                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feature) Reset() {
	*x = Feature{}
	mi := &file_routeguide_routeguide_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_routeguide_routeguide_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_routeguide_routeguide_proto_rawDescGZIP(), []int{1}
}

func (x *Feature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Feature) GetLocation() *Point {
	if x != nil {
		return x.Location
	}
	return nil
}

type Rectangle struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BottomLeftCorner *Point                 `protobuf:"bytes,1,opt,name=bottomLeftCorner,proto3" json:"bottomLeftCorner,omitempty"`
	TopRightCorner   *Point                 `protobuf:"bytes,2,opt,name=topRightCorner,proto3" json:"topRightCorner,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Rectangle) Reset() {
	*x = Rectangle{}
	mi := &file_routeguide_routeguide_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rectangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rectangle) ProtoMessage() {}

func (x *Rectangle) ProtoReflect() protoreflect.Message {
	mi := &file_routeguide_routeguide_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rectangle.ProtoReflect.Descriptor instead.
func (*Rectangle) Descriptor() ([]byte, []int) {
	return file_routeguide_routeguide_proto_rawDescGZIP(), []int{2}
}

func (x *Rectangle) GetBottomLeftCorner() *Point {
	if x != nil {
		return x.BottomLeftCorner
	}
	return nil
}

func (x *Rectangle) GetTopRightCorner() *Point {
	if x != nil {
		return x.TopRightCorner
	}
	return nil
}

type RouteSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PointCount    int32                  `protobuf:"varint,1,opt,name=point_count,json=pointCount,proto3" json:"point_count,omitempty"`
	FeatureCount  int32                  `protobuf:"varint,2,opt,name=feature_count,json=featureCount,proto3" json:"feature_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteSummary) Reset() {
	*x = RouteSummary{}
	mi := &file_routeguide_routeguide_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteSummary) ProtoMessage() {}

func (x *RouteSummary) ProtoReflect() protoreflect.Message {
	mi := &file_routeguide_routeguide_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteSummary.ProtoReflect.Descriptor instead.
func (*RouteSummary) Descriptor() ([]byte, []int) {
	return file_routeguide_routeguide_proto_rawDescGZIP(), []int{3}
}

func (x *RouteSummary) GetPointCount() int32 {
	if x != nil {
		return x.PointCount
	}
	return 0
}

func (x *RouteSummary) GetFeatureCount() int32 {
	if x != nil {
		return x.FeatureCount
	}
	return 0
}

var File_routeguide_routeguide_proto protoreflect.FileDescriptor

const file_routeguide_routeguide_proto_rawDesc = "" +
	"\n" +
	"\x1brouteguide/routeguide.proto\x12\n" +
	"routeguide\"A\n" +
	"\x05Point\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x05R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x05R\tlongitude\"L\n" +
	"\aFeature\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\blocation\x18\x02 \x01(\v2\x11.routeguide.PointR\blocation\"\x85\x01\n" +
	"\tRectangle\x12=\n" +
	"\x10bottomLeftCorner\x18\x01 \x01(\v2\x11.routeguide.PointR\x10bottomLeftCorner\x129\n" +
	"\x0etopRightCorner\x18\x02 \x01(\v2\x11.routeguide.PointR\x0etopRightCorner\"T\n" +
	"\fRouteSummary\x12\x1f\n" +
	"\vpoint_count\x18\x01 \x01(\x05R\n" +
	"pointCount\x12#\n" +
	"\rfeature_count\x18\x02 \x01(\x05R\ffeatureCount2\xc4\x01\n" +
	"\n" +
	"RouteGuide\x126\n" +
	"\n" +
	"GetFeature\x12\x11.routeguide.Point\x1a\x13.routeguide.Feature\"\x00\x12>\n" +
	"\fListFeatures\x12\x15.routeguide.Rectangle\x1a\x13.routeguide.Feature\"\x000\x01\x12>\n" +
	"\vRecordRoute\x12\x11.routeguide.Point\x1a\x18.routeguide.RouteSummary\"\x00(\x01B\x17Z\x15routeguide/routeguideb\x06proto3"

var (
	file_routeguide_routeguide_proto_rawDescOnce sync.Once
	file_routeguide_routeguide_proto_rawDescData []byte
)

func file_routeguide_routeguide_proto_rawDescGZIP() []byte {
	file_routeguide_routeguide_proto_rawDescOnce.Do(func() {
		file_routeguide_routeguide_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeguide_routeguide_proto_rawDesc), len(file_routeguide_routeguide_proto_rawDesc)))
	})
	return file_routeguide_routeguide_proto_rawDescData
}

var file_routeguide_routeguide_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_routeguide_routeguide_proto_goTypes = []any{
	(*Point)(nil),        // 0: routeguide.Point
	(*Feature)(nil),      // 1: routeguide.Feature
	(*Rectangle)(nil),    // 2: routeguide.Rectangle
	(*RouteSummary)(nil), // 3: routeguide.RouteSummary
}
var file_routeguide_routeguide_proto_depIdxs = []int32{
	0, // 0: routeguide.Feature.location:type_name -> routeguide.Point
	0, // 1: routeguide.Rectangle.bottomLeftCorner:type_name -> routeguide.Point
	0, // 2: routeguide.Rectangle.topRightCorner:type_name -> routeguide.Point
	0, // 3: routeguide.RouteGuide.GetFeature:input_type -> routeguide.Point
	2, // 4: routeguide.RouteGuide.ListFeatures:input_type -> routeguide.Rectangle
	0, // 5: routeguide.RouteGuide.RecordRoute:input_type -> routeguide.Point
	1, // 6: routeguide.RouteGuide.GetFeature:output_type -> routeguide.Feature
	1, // 7: routeguide.RouteGuide.ListFeatures:output_type -> routeguide.Feature
	3, // 8: routeguide.RouteGuide.RecordRoute:output_type -> routeguide.RouteSummary
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_routeguide_routeguide_proto_init() }
func file_routeguide_routeguide_proto_init() {
	if File_routeguide_routeguide_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeguide_routeguide_proto_rawDesc), len(file_routeguide_routeguide_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routeguide_routeguide_proto_goTypes,
		DependencyIndexes: file_routeguide_routeguide_proto_depIdxs,
		MessageInfos:      file_routeguide_routeguide_proto_msgTypes,
	}.Build()
	File_routeguide_routeguide_proto = out.File
	file_routeguide_routeguide_proto_goTypes = nil
	file_routeguide_routeguide_proto_depIdxs = nil
}
